### ISSUE TITLE
Version 5.3.3 throws errors in composer

### ISSUE THREAD

**Issue by gb5256** [GrabzIt/grabzit-php#2]
When doing a composer update I get this error:

In ClassMapGenerator.php line 129:

  Could not scan for classes inside "/var/www/vendor/grabzit/grabzit/vendor/" which does not appear to be a file nor a folder

I have read somewhere that this is likely an issue in the auto loader section.

5.3.2 works without issues.

**Comment by GrabzIt** [comment]
Thanks for raising this, we will get a fix out asap.

**Comment by GrabzIt** [comment]
It should be fixed now, please can you give it a go.
